// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL3YQzDJmgQGmWbHBunqo9rCWVAHLHASI',
    appId: '1:846839399690:web:94add37db6a61db56ea6f3',
    messagingSenderId: '846839399690',
    projectId: 'ragfree-1d159',
    authDomain: 'ragfree-1d159.firebaseapp.com',
    storageBucket: 'ragfree-1d159.firebasestorage.app',
    measurementId: 'G-WSZGSJ31G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnMp9UNbRT1F7HoOviu7WYiTifW5MNW0I',
    appId: '1:846839399690:android:0254b0fec708bb256ea6f3',
    messagingSenderId: '846839399690',
    projectId: 'ragfree-1d159',
    storageBucket: 'ragfree-1d159.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgpg1duwA-ibT_XhZJS_NSjCItB9sxBng',
    appId: '1:846839399690:ios:185ab1916b9683ea6ea6f3',
    messagingSenderId: '846839399690',
    projectId: 'ragfree-1d159',
    storageBucket: 'ragfree-1d159.firebasestorage.app',
    iosBundleId: 'com.example.ragfreePlusFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgpg1duwA-ibT_XhZJS_NSjCItB9sxBng',
    appId: '1:846839399690:ios:185ab1916b9683ea6ea6f3',
    messagingSenderId: '846839399690',
    projectId: 'ragfree-1d159',
    storageBucket: 'ragfree-1d159.firebasestorage.app',
    iosBundleId: 'com.example.ragfreePlusFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL3YQzDJmgQGmWbHBunqo9rCWVAHLHASI',
    appId: '1:846839399690:web:7f231edbab2b84e06ea6f3',
    messagingSenderId: '846839399690',
    projectId: 'ragfree-1d159',
    authDomain: 'ragfree-1d159.firebaseapp.com',
    storageBucket: 'ragfree-1d159.firebasestorage.app',
    measurementId: 'G-JXR49FLPKX',
  );
}
